<a href="https://colab.research.google.com/github/Vijayvarma115/Data-Science-Gen-AI-Playlist-2024/blob/main/bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
np1=np.array([1,2,3,4])
print(np1)
print(type(np1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
n=np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
print(n)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(type(n))
n[1][1]=15
print(n)

<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5 15  7  8]]


In [8]:
print(len(n))

2


In [9]:
r=np.zeros((3,3))
print(r)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
r=np.ones((3,3))
print(r)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
r=np.ones((3,3),dtype='int')
print(r)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
r2=np.full((3,3),2)
print(r2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Intro to PANDAS

In [13]:
import pandas as pd
import numpy as np

In [14]:
arr=np.array([1,2,3,4,5])


In [15]:
dfs=pd.Series(arr)

In [16]:
dfs

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
data={'Name':['Raj','Sheldon','Joey','Bharath','Vamsi','Soumya'],'Age':[19,17,22,23,43,45]}

In [18]:
df=pd.DataFrame(data)

In [19]:
df

Name  Age
0      Raj   19
1  Sheldon   17
2     Joey   22
3  Bharath   23
4    Vamsi   43
5   Soumya   45

In [20]:
df.head()#printing 1st 5 values or rows?

Name  Age
0      Raj   19
1  Sheldon   17
2     Joey   22
3  Bharath   23
4    Vamsi   43

In [21]:
df.tail()#last 5 rows

Name  Age
1  Sheldon   17
2     Joey   22
3  Bharath   23
4    Vamsi   43
5   Soumya   45

In [22]:
#if required customable rows
df.head(6)

Name  Age
0      Raj   19
1  Sheldon   17
2     Joey   22
3  Bharath   23
4    Vamsi   43
5   Soumya   45

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    6 non-null      object
 1   Age     6 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 224.0+ bytes


In [24]:
df.describe()

Age
count   6.000000
mean   28.166667
std    12.464617
min    17.000000
25%    19.750000
50%    22.500000
75%    38.000000
max    45.000000

In [25]:
df[0:1]

Name  Age
0  Raj   19

In [26]:
 df.iloc[0:1,0]

0    Raj
Name: Name, dtype: object

In [27]:
df['new']=[5,6,7,8,9,10]


In [28]:
df

Name  Age  new
0      Raj   19    5
1  Sheldon   17    6
2     Joey   22    7
3  Bharath   23    8
4    Vamsi   43    9
5   Soumya   45   10

In [29]:
df.rename(columns={'new':'class'},inplace=1)

In [30]:
df


Name  Age  class
0      Raj   19      5
1  Sheldon   17      6
2     Joey   22      7
3  Bharath   23      8
4    Vamsi   43      9
5   Soumya   45     10

In [31]:
df1=df

In [32]:
df1


Name  Age  class
0      Raj   19      5
1  Sheldon   17      6
2     Joey   22      7
3  Bharath   23      8
4    Vamsi   43      9
5   Soumya   45     10

In [33]:
df2=df.copy()

In [34]:
df2

Name  Age  class
0      Raj   19      5
1  Sheldon   17      6
2     Joey   22      7
3  Bharath   23      8
4    Vamsi   43      9
5   Soumya   45     10

In [36]:
df=pd.read_csv('/content/spotify-2023.csv',encoding='latin1')

In [37]:
df.head()

track_name    artist(s)_name  artist_count  \
0  Seven (feat. Latto) (Explicit Ver.)  Latto, Jung Kook             2   
1                                 LALA       Myke Towers             1   
2                              vampire    Olivia Rodrigo             1   
3                         Cruel Summer      Taylor Swift             1   
4                       WHERE SHE GOES         Bad Bunny             1   

   released_year  released_month  released_day  in_spotify_playlists  \
0           2023               7            14                   553   
1           2023               3            23                  1474   
2           2023               6            30                  1397   
3           2019               8            23                  7858   
4           2023               5            18                  3133   

   in_spotify_charts    streams  in_apple_playlists  ...  bpm key   mode  \
0                147  141381703                  43  ...  125   B  Major   
1                 48  133716286                  48  ...   92  C#  Major   
2                113  140003974                  94  ...  138   F  Major   
3                100  800840817                 116  ...  170   A  Major   
4                 50  303236322                  84  ...  144   A  Minor   

  danceability_%  valence_% energy_% acousticness_%  instrumentalness_%  \
0             80         89       83             31                   0   
1             71         61       74              7                   0   
2             51         32       53             17                   0   
3             55         58       72             11                   0   
4             65         23       80             14                  63   

   liveness_%  speechiness_%  
0           8              4  
1          10              4  
2          31              6  
3          11             15  
4          11              6  

[5 rows x 24 columns]

In [38]:
df.head(10)

track_name              artist(s)_name  \
0  Seven (feat. Latto) (Explicit Ver.)            Latto, Jung Kook   
1                                 LALA                 Myke Towers   
2                              vampire              Olivia Rodrigo   
3                         Cruel Summer                Taylor Swift   
4                       WHERE SHE GOES                   Bad Bunny   
5                             Sprinter           Dave, Central Cee   
6                      Ella Baila Sola  Eslabon Armado, Peso Pluma   
7                             Columbia                     Quevedo   
8                             fukumean                       Gunna   
9                      La Bebe - Remix       Peso Pluma, Yng Lvcas   

   artist_count  released_year  released_month  released_day  \
0             2           2023               7            14   
1             1           2023               3            23   
2             1           2023               6            30   
3             1           2019               8            23   
4             1           2023               5            18   
5             2           2023               6             1   
6             2           2023               3            16   
7             1           2023               7             7   
8             1           2023               5            15   
9             2           2023               3            17   

   in_spotify_playlists  in_spotify_charts    streams  in_apple_playlists  \
0                   553                147  141381703                  43   
1                  1474                 48  133716286                  48   
2                  1397                113  140003974                  94   
3                  7858                100  800840817                 116   
4                  3133                 50  303236322                  84   
5                  2186                 91  183706234                  67   
6                  3090                 50  725980112                  34   
7                   714                 43   58149378                  25   
8                  1096                 83   95217315                  60   
9                  2953                 44  553634067                  49   

   ...  bpm key   mode danceability_%  valence_% energy_% acousticness_%  \
0  ...  125   B  Major             80         89       83             31   
1  ...   92  C#  Major             71         61       74              7   
2  ...  138   F  Major             51         32       53             17   
3  ...  170   A  Major             55         58       72             11   
4  ...  144   A  Minor             65         23       80             14   
5  ...  141  C#  Major             92         66       58             19   
6  ...  148   F  Minor             67         83       76             48   
7  ...  100   F  Major             67         26       71             37   
8  ...  130  C#  Minor             85         22       62             12   
9  ...  170   D  Minor             81         56       48             21   

   instrumentalness_%  liveness_%  speechiness_%  
0                   0           8              4  
1                   0          10              4  
2                   0          31              6  
3                   0          11             15  
4                  63          11              6  
5                   0           8             24  
6                   0           8              3  
7                   0          11              4  
8                   0          28              9  
9                   0           8             33  

[10 rows x 24 columns]

In [39]:
df.tail(20)

track_name               artist(s)_name  artist_count  \
933                 Vigilante Shit                 Taylor Swift             1   
934                   Question...?                 Taylor Swift             1   
935                          On BS             Drake, 21 Savage             2   
936                     Mastermind                 Taylor Swift             1   
937                     Circo Loco             Drake, 21 Savage             2   
938                      Labyrinth                 Taylor Swift             1   
939                    Spin Bout U             Drake, 21 Savage             2   
940                  Sweet Nothing                 Taylor Swift             1   
941  Would've, Could've, Should've                 Taylor Swift             1   
942                   Con La Brisa  Ludwig Goransson, Foudeqush             2   
943             Privileged Rappers             Drake, 21 Savage             2   
944                  The Astronaut                          Jin             1   
945                BackOutsideBoyz                        Drake             1   
946                     Broke Boys             Drake, 21 Savage             2   
947                  The Great War                 Taylor Swift             1   
948                   My Mind & Me                 Selena Gomez             1   
949      Bigger Than The Whole Sky                 Taylor Swift             1   
950           A Veces (feat. Feid)           Feid, Paulo Londra             2   
951                  En La De Ella           Feid, Sech, Jhayco             3   
952                          Alone                    Burna Boy             1   

     released_year  released_month  released_day  in_spotify_playlists  \
933           2022              10            21                  1948   
934           2022              10            21                  1608   
935           2022              11             4                  1338   
936           2022              10            21                  1936   
937           2022              11             4                  1794   
938           2022              10            21                  1597   
939           2022              11             4                  1652   
940           2022              10            21                  1747   
941           2022              10            21                  1715   
942           2022              11             4                   486   
943           2022              11             4                  1007   
944           2022              10            28                   481   
945           2022              11             4                  1045   
946           2022              11             4                  1060   
947           2022              10            21                  1274   
948           2022              11             3                   953   
949           2022              10            21                  1180   
950           2022              11             3                   573   
951           2022              10            20                  1320   
952           2022              11             4                   782   

     in_spotify_charts    streams  in_apple_playlists  ...  bpm  key   mode  \
933                  0  253650850                  12  ...   80    E  Minor   
934                  0  223064273                  10  ...  109    G  Major   
935                  0  170413877                   9  ...  158    A  Major   
936                  0  218320587                   7  ...  126    E  Major   
937                  0  141720999                  26  ...  104   C#  Major   
938                  0  187339835                   6  ...  110  NaN  Major   
939                  2  198365537                  26  ...  130    G  Major   
940                  0  186104310                   9  ...  177  NaN  Major   
941                  0  177503916                   4  .

In [40]:
df.shape

(953, 24)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64 
 3   released_year         953 non-null    int64 
 4   released_month        953 non-null    int64 
 5   released_day          953 non-null    int64 
 6   in_spotify_playlists  953 non-null    int64 
 7   in_spotify_charts     953 non-null    int64 
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64 
 10  in_apple_charts       953 non-null    int64 
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64 
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64 
 15  key                   858 non-null    ob

In [42]:
df.columns

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm',
       'key', 'mode', 'danceability_%', 'valence_%', 'energy_%',
       'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%'],
      dtype='object')

In [43]:
df.isnull()

track_name  artist(s)_name  artist_count  released_year  released_month  \
0         False           False         False          False           False   
1         False           False         False          False           False   
2         False           False         False          False           False   
3         False           False         False          False           False   
4         False           False         False          False           False   
..          ...             ...           ...            ...             ...   
948       False           False         False          False           False   
949       False           False         False          False           False   
950       False           False         False          False           False   
951       False           False         False          False           False   
952       False           False         False          False           False   

     released_day  in_spotify_playlists  in_spotify_charts  streams  \
0           False                 False              False    False   
1           False                 False              False    False   
2           False                 False              False    False   
3           False                 False              False    False   
4           False                 False              False    False   
..            ...                   ...                ...      ...   
948         False                 False              False    False   
949         False                 False              False    False   
950         False                 False              False    False   
951         False                 False              False    False   
952         False                 False              False    False   

     in_apple_playlists  ...    bpm    key   mode  danceability_%  valence_%  \
0                 False  ...  False  False  False           False      False   
1                 False  ...  False  False  False           False      False   
2                 False  ...  False  False  False           False      False   
3                 False  ...  False  False  False           False      False   
4                 False  ...  False  False  False           False      False   
..                  ...  ...    ...    ...    ...             ...        ...   
948               False  ...  False  False  False           False      False   
949               False  ...  False  False  False           False      False   
950               False  ...  False  False  False           False      False   
951               False  ...  False  False  False           False      False   
952               False  ...  False  False  False           False      False   

     energy_%  acousticness_%  instrumentalness_%  liveness_%  speechiness_%  
0       False           False               False       False          False  
1       False           False               False       False          False  
2       False           False               False       False          False  
3       False           False               False       False          False  
4       False           False               False       False          False  
..        ...             ...                 ...         ...            ...  
948     False           False               False       False          False  
949     False           False               False       False          False  
950     False           False               False       False          False  
951     False           False               False       False          False  
952     False           False               False       False          False  

[953 rows x 24 columns]

In [44]:
df.isnull().sum()

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

In [45]:
df.dropna(inplace=True)

In [46]:
df.isnull().sum()

track_name              0
artist(s)_name          0
artist_count            0
released_year           0
released_month          0
released_day            0
in_spotify_playlists    0
in_spotify_charts       0
streams                 0
in_apple_playlists      0
in_apple_charts         0
in_deezer_playlists     0
in_deezer_charts        0
in_shazam_charts        0
bpm                     0
key                     0
mode                    0
danceability_%          0
valence_%               0
energy_%                0
acousticness_%          0
instrumentalness_%      0
liveness_%              0
speechiness_%           0
dtype: int64

In [58]:
df.head()

track_name    artist(s)_name  artist_count  \
0  Seven (feat. Latto) (Explicit Ver.)  Latto, Jung Kook             2   
1                                 LALA       Myke Towers             1   
2                              vampire    Olivia Rodrigo             1   
3                         Cruel Summer      Taylor Swift             1   
4                       WHERE SHE GOES         Bad Bunny             1   

   released_year  released_month  released_day  in_spotify_playlists  \
0           2023               7            14                   553   
1           2023               3            23                  1474   
2           2023               6            30                  1397   
3           2019               8            23                  7858   
4           2023               5            18                  3133   

   in_spotify_charts    streams   mode  danceability_%  energy_%  
0                147  141381703  Major              80        83  
1                 48  133716286  Major              71        74  
2                113  140003974  Major              51        53  
3                100  800840817  Major              55        72  
4                 50  303236322  Minor              65        80

In [59]:
df.columns

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'mode', 'danceability_%', 'energy_%'],
      dtype='object')

In [60]:
# df.drop(['in_apple_playlists','in_apple_charts','in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm',
#        'key','instrumentalness_%','acousticness_%','liveness_%', 'speechiness_%', 'valence_%'],axis=1)

In [63]:
pd.DataFrame(df['artist(s)_name'].str.split(' , ').sum()).value_counts()

Taylor Swift                          29
SZA                                   17
Bad Bunny                             16
The Weeknd                            15
Harry Styles                          12
                                      ..
J Balvin, Bad Bunny                    1
Israel & Rodolffo, Mari Fernandez      1
Israel & Rodolffo, Ana Castela         1
Intense, AP Dhillon, Gurinder Gill     1
teto                                   1
Name: count, Length: 571, dtype: int64

In [66]:
df.sort_values(by='streams',ascending=False)

track_name      artist(s)_name  \
574      Love Grows (Where My Rosemary Goes)   Edison Lighthouse   
33                                 Anti-Hero        Taylor Swift   
253                            Glimpse of Us                Joji   
455                           Seek & Destroy                 SZA   
98                        Summertime Sadness        Lana Del Rey   
..                                       ...                 ...   
750                                  Falling        Harry Styles   
366                                  Revenge        XXXTENTACION   
744                                 Right On            Lil Baby   
515                             Best Friends          The Weeknd   
301  Arc��ngel: Bzrp Music Sessions, Vol  Arcangel, Bizarrap   

     artist_count  released_year  released_month  released_day  \
574             1           1970               1             1   
33              1           2022              10            21   
253             1           2022               6            10   
455             1           2022              12             9   
98              1           2011               1             1   
..            ...            ...             ...           ...   
750             1           2019              12            13   
366             1           2017               8            25   
744             1           2022               4             8   
515             1           2022               1             7   
301             2           2023               3            22   

     in_spotify_playlists  in_spotify_charts  \
574                  2877                  0   
33                   9082                 56   
253                  6330                  6   
455                  1007                  0   
98                  20333                 52   
..                    ...                ...   
750                  7556                  0   
366                  3600                 11   
744                  1116                  0   
515                  1292                  0   
301                   654                  3   

                                               streams   mode  danceability_%  \
574  BPM110KeyAModeMajorDanceability53Valence75Ener...  Major              53   
33                                           999748277  Major              64   
253                                          988515741  Major              44   
455                                           98709329  Major              65   
98                                           983637508  Minor              56   
..                                                 ...    ...             ...   
750                                         1023187129  Major              57   
366                                         1022258230  Minor              75   
744                                          101780047  Major              70   
515                                          101114984  Minor              49   
301                                          100409613  Minor              72   

     energy_%  
574        69  
33         63  
253        32  
455        65  
98         66  
..        ...  
750        27  
366        25  
744        61  
515        59  
301        78  

[817 rows x 12 columns]

In [67]:
df.sort_values(by='in_spotify_playlists',ascending=False)

track_name  \
757                      Get Lucky - Radio Edit   
630                              Mr. Brightside   
720                     Wake Me Up - Radio Edit   
624   Smells Like Teen Spirit - Remastered 2021   
199                                  Take On Me   
..                                          ...   
104                                   New Jeans   
185                                     Cheques   
112                                     LAGUNAS   
327  Peaches (from The Super Mario Bros. Movie)   
94                               Still With You   

                                 artist(s)_name  artist_count  released_year  \
757  Pharrell Williams, Nile Rodgers, Daft Punk             3           2013   
630                                 The Killers             1           2003   
720                                      Avicii             1           2013   
624                                     Nirvana             1           1991   
199                                        a-ha             1           1984   
..                                          ...           ...            ...   
104                                    NewJeans             1           2023   
185                                       Shubh             1           2023   
112                   Jasiel Nu��ez, Peso P             2           2023   
327                                  Jack Black             1           2023   
94                                    Jung Kook             1           2020   

     released_month  released_day  in_spotify_playlists  in_spotify_charts  \
757               1             1                 52898                  0   
630               9            23                 51979                 15   
720               1             1                 50887                 34   
624               9            10                 49991                  9   
199              10            19                 44927                 17   
..              ...           ...                   ...                ...   
104               7             7                    77                 35   
185               5            19                    67                  8   
112               6            22                    58                 18   
327               4             7                    34                  0   
94                6             5                    31                 39   

        streams   mode  danceability_%  energy_%  
757   933815613  Minor              79        81  
630  1806617704  Major              35        93  
720  1970673297  Major              53        78  
624  1690192927  Major              52        91  
199  1479115056  Minor              57        90  
..          ...    ...             ...       ...  
104    29562220  Minor              81        72  
185    47956378  Minor              74        63  
112    39058561  Major              77        62  
327    68216992  Minor              71        31  
94     38411956  Minor              53        47  

[817 rows x 12 columns]

In [68]:
df.to_csv('final.csv')

In [69]:
df

track_name      artist(s)_name  artist_count  \
0    Seven (feat. Latto) (Explicit Ver.)    Latto, Jung Kook             2   
1                                   LALA         Myke Towers             1   
2                                vampire      Olivia Rodrigo             1   
3                           Cruel Summer        Taylor Swift             1   
4                         WHERE SHE GOES           Bad Bunny             1   
..                                   ...                 ...           ...   
948                         My Mind & Me        Selena Gomez             1   
949            Bigger Than The Whole Sky        Taylor Swift             1   
950                 A Veces (feat. Feid)  Feid, Paulo Londra             2   
951                        En La De Ella  Feid, Sech, Jhayco             3   
952                                Alone           Burna Boy             1   

     released_year  released_month  released_day  in_spotify_playlists  \
0             2023               7            14                   553   
1             2023               3            23                  1474   
2             2023               6            30                  1397   
3             2019               8            23                  7858   
4             2023               5            18                  3133   
..             ...             ...           ...                   ...   
948           2022              11             3                   953   
949           2022              10            21                  1180   
950           2022              11             3                   573   
951           2022              10            20                  1320   
952           2022              11             4                   782   

     in_spotify_charts    streams   mode  danceability_%  energy_%  
0                  147  141381703  Major              80        83  
1                   48  133716286  Major              71        74  
2                  113  140003974  Major              51        53  
3                  100  800840817  Major              55        72  
4                   50  303236322  Minor              65        80  
..                 ...        ...    ...             ...       ...  
948                  0   91473363  Major              60        39  
949                  0  121871870  Major              42        24  
950                  0   73513683  Major              80        67  
951                  0  133895612  Major              82        77  
952                  2   96007391  Minor              61        67  

[817 rows x 12 columns]

In [75]:
df.drop(['in_spotify_charts'],axis=1,inplace=True)

In [76]:
df

track_name      artist(s)_name  artist_count  \
0    Seven (feat. Latto) (Explicit Ver.)    Latto, Jung Kook             2   
1                                   LALA         Myke Towers             1   
2                                vampire      Olivia Rodrigo             1   
3                           Cruel Summer        Taylor Swift             1   
4                         WHERE SHE GOES           Bad Bunny             1   
..                                   ...                 ...           ...   
948                         My Mind & Me        Selena Gomez             1   
949            Bigger Than The Whole Sky        Taylor Swift             1   
950                 A Veces (feat. Feid)  Feid, Paulo Londra             2   
951                        En La De Ella  Feid, Sech, Jhayco             3   
952                                Alone           Burna Boy             1   

     released_year  released_month  released_day  in_spotify_playlists  \
0             2023               7            14                   553   
1             2023               3            23                  1474   
2             2023               6            30                  1397   
3             2019               8            23                  7858   
4             2023               5            18                  3133   
..             ...             ...           ...                   ...   
948           2022              11             3                   953   
949           2022              10            21                  1180   
950           2022              11             3                   573   
951           2022              10            20                  1320   
952           2022              11             4                   782   

       streams   mode  danceability_%  energy_%  
0    141381703  Major              80        83  
1    133716286  Major              71        74  
2    140003974  Major              51        53  
3    800840817  Major              55        72  
4    303236322  Minor              65        80  
..         ...    ...             ...       ...  
948   91473363  Major              60        39  
949  121871870  Major              42        24  
950   73513683  Major              80        67  
951  133895612  Major              82        77  
952   96007391  Minor              61        67  

[817 rows x 11 columns]

In [80]:
df.to_csv('final.csv',index=False)

In [82]:
df.drop(['energy_%'],axis=1,inplace=True)

In [83]:
df.to_csv('final.csv')

In [84]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
